# Site settings
title: Andrew Jiang
email: andrewji@usc.edu
description: Andrew's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewjiang.com" # the base hostname & protocol for your site
twitter_username: ninjiangstar
github_username:  ninjiangstar

permalink: /:categories/:title

nav: [Code, Design, Misc, Blog]

# Build settings
markdown: kramdown

